# Variables
base_url = "https://topfour.net"
title = "Top Four"
author = "Peter's Path"
description = "The community directory for personal Top 4 lists. Share your ranked favorites: movies, albums, snacks, games and more. What is your Top 4?"

# Settings
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
tags = "top 4, top four, top 4 lists, personal rankings, favorite movies, best albums, top books, favorite snacks, best games, top video games, best productivity tools, favorite comfort foods"
socialimage = "https://topfour.net/images/social-image.jpg"
